site_name: "ComCat Lab Welcome Guide"
repo_url: https://github.com/ComCatLab/welcome-guide
edit_uri: docs/sources
site_author: "Ugochukwu Nwosu"

nav:
  - Overview:
    - Home: index.md
    - Quickstart: quickstart.md
  - On-Boarding:
    - 'onboarding/index.md'
    - 'onboarding/basic_setup.md'
    - 'onboarding/development.md'
    - 'onboarding/intro_to_ase.md'
    - 'onboarding/cluster_setup.md'
  - nutshell.md
  - 'software_pages.md'
  - Samples:
    - 'samples/python.md'
    - 'Bash Profile': 'samples/bash.md'
    - 'samples/slurm.md'
  - Tutorials:
    - Intro: 'tutorials/index.md'
    - 'tutorials/ccdb.md'
    - 'tutorials/data_transfer.md'
    - 'tutorials/first_calc.md'
    - 'tutorials/espresso_compilation.md'
    - 'tutorials/optimizing_requests.md'
    - 'tutorials/vasp_ir.md'
  - Additional Resources:
    - 'resources/troubleshooting.md'
    - 'resources/snippets.md'
    - 'resources/links.md'
  - 'Development Guide':
    - 'Setting Up': 'dev_guide/setup.md'
    - Contributing: 'dev_guide/contributing.md'
    - 'dev_guide/docs.md'
    - 'dev_guide/testing.md'
    - 'dev_guide/code_of_conduct.md'

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select

docs_dir: docs/sources

site_dir: docs/site

markdown_extensions:
  - admonition
  - attr_list
  - mdx_truly_sane_lists:
      nested_indent: 4
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
- search
- git-revision-date
